version: 2.1
workflows:
  version: 2
  build:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: circleci/node:18.16.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            cd ecoupon-manager-backend
            npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          name: Build and test
          command: npm run build && npm test
